In [17]:
import numpy as np
from sklearn import datasets

In [18]:
iris = datasets.load_iris()
X = iris.data
y = iris.target.copy()
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
y[y!=0] = 1
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

logistic_regression = LogisticRegression()
logistic_regression.fit(X_train,y_train)
y_predict = logistic_regression.predict(X_test)

# 手动实现

In [21]:
TN = np.sum((y_predict==0)&(y_test==0))
TN

10

In [22]:
FP = np.sum((y_predict==1)&(y_test==0))
FP

0

In [23]:
FN = np.sum((y_predict==0)&(y_test==1))
FN

0

In [24]:
TP = np.sum((y_predict==1)&(y_test==1))
TP

28

In [25]:
confusion_matrix = np.array([
    [TN, FP],
    [FN, TP]
])

confusion_matrix

array([[10,  0],
       [ 0, 28]])

In [26]:
precision = TP/ (TP+FP)
precision

1.0

In [27]:
recall = TP/(FN+TP)
recall

1.0

In [28]:
f1_score = 2*precision*recall /(precision+recall)
f1_score

1.0

# scikit-learn封装实现

In [29]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_predict)

array([[10,  0],
       [ 0, 28]])

In [30]:
from sklearn.metrics import precision_score

precision_score(y_test,y_predict)

1.0

In [31]:
from sklearn.metrics import recall_score

recall_score(y_test,y_predict)

1.0

In [32]:
from sklearn.metrics import f1_score

f1_score(y_test,y_predict)

1.0