### Numpy的矩阵运算有何不同

In [56]:
n = 5000000
x = [i for i in range(n)]

In [2]:
x

[0, 1, 2, 3, 4]

In [3]:
x * 2

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [4]:
x + x

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [57]:
%%time
y = [i * 2 for i in x]

CPU times: user 161 ms, sys: 48.2 ms, total: 209 ms
Wall time: 207 ms


In [6]:
y

[0, 2, 4, 6, 8]

In [58]:
import numpy as np
X = np.arange(n)
X

array([      0,       1,       2, ..., 4999997, 4999998, 4999999])

In [59]:
%%time
Y = X * 2

CPU times: user 7.95 ms, sys: 0 ns, total: 7.95 ms
Wall time: 7.46 ms


In [60]:
Y[:10]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 一元运算

In [10]:
X = np.arange(1, 11, 0.5).reshape(4, 5)
X

array([[ 1. ,  1.5,  2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5, 10. , 10.5]])

In [11]:
np.abs(X)

array([[ 1. ,  1.5,  2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5, 10. , 10.5]])

In [12]:
np.sqrt(X)

array([[1.        , 1.22474487, 1.41421356, 1.58113883, 1.73205081],
       [1.87082869, 2.        , 2.12132034, 2.23606798, 2.34520788],
       [2.44948974, 2.54950976, 2.64575131, 2.73861279, 2.82842712],
       [2.91547595, 3.        , 3.082207  , 3.16227766, 3.24037035]])

In [13]:
np.square(X)

array([[  1.  ,   2.25,   4.  ,   6.25,   9.  ],
       [ 12.25,  16.  ,  20.25,  25.  ,  30.25],
       [ 36.  ,  42.25,  49.  ,  56.25,  64.  ],
       [ 72.25,  81.  ,  90.25, 100.  , 110.25]])

In [14]:
np.exp(X)

array([[2.71828183e+00, 4.48168907e+00, 7.38905610e+00, 1.21824940e+01,
        2.00855369e+01],
       [3.31154520e+01, 5.45981500e+01, 9.00171313e+01, 1.48413159e+02,
        2.44691932e+02],
       [4.03428793e+02, 6.65141633e+02, 1.09663316e+03, 1.80804241e+03,
        2.98095799e+03],
       [4.91476884e+03, 8.10308393e+03, 1.33597268e+04, 2.20264658e+04,
        3.63155027e+04]])

In [15]:
np.log(X)

array([[0.        , 0.40546511, 0.69314718, 0.91629073, 1.09861229],
       [1.25276297, 1.38629436, 1.5040774 , 1.60943791, 1.70474809],
       [1.79175947, 1.87180218, 1.94591015, 2.01490302, 2.07944154],
       [2.14006616, 2.19722458, 2.2512918 , 2.30258509, 2.35137526]])

In [16]:
np.log2(X)

array([[0.        , 0.5849625 , 1.        , 1.32192809, 1.5849625 ],
       [1.80735492, 2.        , 2.169925  , 2.32192809, 2.45943162],
       [2.5849625 , 2.70043972, 2.80735492, 2.9068906 , 3.        ],
       [3.08746284, 3.169925  , 3.24792751, 3.32192809, 3.39231742]])

In [17]:
np.log10(X)

array([[0.        , 0.17609126, 0.30103   , 0.39794001, 0.47712125],
       [0.54406804, 0.60205999, 0.65321251, 0.69897   , 0.74036269],
       [0.77815125, 0.81291336, 0.84509804, 0.87506126, 0.90308999],
       [0.92941893, 0.95424251, 0.97772361, 1.        , 1.0211893 ]])

In [18]:
X

array([[ 1. ,  1.5,  2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5, 10. , 10.5]])

In [19]:
np.ceil(X)

array([[ 1.,  2.,  2.,  3.,  3.],
       [ 4.,  4.,  5.,  5.,  6.],
       [ 6.,  7.,  7.,  8.,  8.],
       [ 9.,  9., 10., 10., 11.]])

In [20]:
np.floor(X)

array([[ 1.,  1.,  2.,  2.,  3.],
       [ 3.,  4.,  4.,  5.,  5.],
       [ 6.,  6.,  7.,  7.,  8.],
       [ 8.,  9.,  9., 10., 10.]])

In [21]:
np.round(X)

array([[ 1.,  2.,  2.,  2.,  3.],
       [ 4.,  4.,  4.,  5.,  6.],
       [ 6.,  6.,  7.,  8.,  8.],
       [ 8.,  9., 10., 10., 10.]])

In [22]:
np.sin(X)

array([[ 0.84147098,  0.99749499,  0.90929743,  0.59847214,  0.14112001],
       [-0.35078323, -0.7568025 , -0.97753012, -0.95892427, -0.70554033],
       [-0.2794155 ,  0.21511999,  0.6569866 ,  0.93799998,  0.98935825],
       [ 0.79848711,  0.41211849, -0.07515112, -0.54402111, -0.87969576]])

In [23]:
np.cos(X)

array([[ 0.54030231,  0.0707372 , -0.41614684, -0.80114362, -0.9899925 ],
       [-0.93645669, -0.65364362, -0.2107958 ,  0.28366219,  0.70866977],
       [ 0.96017029,  0.97658763,  0.75390225,  0.34663532, -0.14550003],
       [-0.6020119 , -0.91113026, -0.99717216, -0.83907153, -0.47553693]])

In [24]:
np.tan(X)

array([[ 1.55740772, 14.10141995, -2.18503986, -0.7470223 , -0.14254654],
       [ 0.37458564,  1.15782128,  4.63733205, -3.38051501, -0.99558405],
       [-0.29100619,  0.2202772 ,  0.87144798,  2.70601387, -6.79971146],
       [-1.32636433, -0.45231566,  0.07536424,  0.64836083,  1.84989999]])

### 二元运算

In [25]:
X + 1

array([[ 2. ,  2.5,  3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ,  8.5,  9. ],
       [ 9.5, 10. , 10.5, 11. , 11.5]])

In [26]:
np.add(X, 1)

array([[ 2. ,  2.5,  3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ,  8.5,  9. ],
       [ 9.5, 10. , 10.5, 11. , 11.5]])

In [27]:
X - 1

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

In [28]:
X * 2

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21.]])

In [29]:
X / 2

array([[0.5 , 0.75, 1.  , 1.25, 1.5 ],
       [1.75, 2.  , 2.25, 2.5 , 2.75],
       [3.  , 3.25, 3.5 , 3.75, 4.  ],
       [4.25, 4.5 , 4.75, 5.  , 5.25]])

In [30]:
2 / X

array([[2.        , 1.33333333, 1.        , 0.8       , 0.66666667],
       [0.57142857, 0.5       , 0.44444444, 0.4       , 0.36363636],
       [0.33333333, 0.30769231, 0.28571429, 0.26666667, 0.25      ],
       [0.23529412, 0.22222222, 0.21052632, 0.2       , 0.19047619]])

In [31]:
X // 2

array([[0., 0., 1., 1., 1.],
       [1., 2., 2., 2., 2.],
       [3., 3., 3., 3., 4.],
       [4., 4., 4., 5., 5.]])

In [32]:
X % 2

array([[1. , 1.5, 0. , 0.5, 1. ],
       [1.5, 0. , 0.5, 1. , 1.5],
       [0. , 0.5, 1. , 1.5, 0. ],
       [0.5, 1. , 1.5, 0. , 0.5]])

In [33]:
X ** 3

array([[1.000000e+00, 3.375000e+00, 8.000000e+00, 1.562500e+01,
        2.700000e+01],
       [4.287500e+01, 6.400000e+01, 9.112500e+01, 1.250000e+02,
        1.663750e+02],
       [2.160000e+02, 2.746250e+02, 3.430000e+02, 4.218750e+02,
        5.120000e+02],
       [6.141250e+02, 7.290000e+02, 8.573750e+02, 1.000000e+03,
        1.157625e+03]])

### 矩阵运算

In [34]:
X = np.linspace(10, 40, 4).reshape(2, 2)
Y = np.linspace(1, 4, 4).reshape(2, 2)

In [35]:
X, Y

(array([[10., 20.],
        [30., 40.]]),
 array([[1., 2.],
        [3., 4.]]))

In [36]:
X + Y

array([[11., 22.],
       [33., 44.]])

In [37]:
X - Y

array([[ 9., 18.],
       [27., 36.]])

In [38]:
X * Y

array([[ 10.,  40.],
       [ 90., 160.]])

In [39]:
X.dot(Y)

array([[ 70., 100.],
       [150., 220.]])

In [40]:
X / Y

array([[10., 10.],
       [10., 10.]])

In [41]:
X.T

array([[10., 30.],
       [20., 40.]])

In [42]:
np.transpose(X)

array([[10., 30.],
       [20., 40.]])

In [43]:
Z = np.linspace(1, 4, 4)
X + Z

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [44]:
Z = np.linspace(1, 4, 2)
X, Z

(array([[10., 20.],
        [30., 40.]]),
 array([1., 4.]))

In [45]:
X + Z

array([[11., 24.],
       [31., 44.]])

In [46]:
X * Z

array([[ 10.,  80.],
       [ 30., 160.]])

In [47]:
Z.dot(X)

array([130., 180.])

In [48]:
X.dot(Z)

array([ 90., 190.])

In [49]:
V = np.linalg.inv(X)

In [50]:
V

array([[-0.2 ,  0.1 ],
       [ 0.15, -0.05]])

In [51]:
X.dot(V)

array([[1.0000000e+00, 0.0000000e+00],
       [4.4408921e-16, 1.0000000e+00]])

In [52]:
V.dot(X)

array([[ 1.00000000e+00,  4.44089210e-16],
       [-1.11022302e-16,  1.00000000e+00]])

In [53]:
np.linalg.inv(np.arange(12).reshape(3, 4))

LinAlgError: Last 2 dimensions of the array must be square

In [54]:
np.linalg.det(X)

-200.0000000000001

In [55]:
np.linalg.eig(X)

(array([-3.72281323, 53.72281323]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))