### 最大最小值

In [1]:
import numpy as np
X = np.arange(5000000)
X

array([      0,       1,       2, ..., 4999997, 4999998, 4999999])

In [2]:
np.min(X)

0

In [3]:
np.max(X)

4999999

In [4]:
%time min(X)

CPU times: user 299 ms, sys: 0 ns, total: 299 ms
Wall time: 299 ms


0

In [5]:
%time np.min(X)

CPU times: user 5.72 ms, sys: 0 ns, total: 5.72 ms
Wall time: 5.23 ms


0

In [6]:
Y = X.reshape(5, -1)
Y

array([[      0,       1,       2, ...,  999997,  999998,  999999],
       [1000000, 1000001, 1000002, ..., 1999997, 1999998, 1999999],
       [2000000, 2000001, 2000002, ..., 2999997, 2999998, 2999999],
       [3000000, 3000001, 3000002, ..., 3999997, 3999998, 3999999],
       [4000000, 4000001, 4000002, ..., 4999997, 4999998, 4999999]])

In [7]:
np.min(Y, axis = 0)

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [8]:
np.min(Y, axis = 1)

array([      0, 1000000, 2000000, 3000000, 4000000])

### 常见统计量

In [9]:
X = np.linspace(1, 20, 20).reshape(4, 5)
X

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

In [10]:
np.sum(X)

210.0

In [11]:
np.sum(X, axis = 0)

array([34., 38., 42., 46., 50.])

In [12]:
np.sum(X, axis = 1)

array([15., 40., 65., 90.])

In [13]:
np.mean(X)

10.5

In [14]:
np.median(X)

10.5

In [15]:
np.std(X)

5.766281297335398

In [16]:
np.var(X)

33.25

In [17]:
Z = np.random.normal(0, 10, 100000)
np.mean(Z), np.std(Z)

(0.012117422295426642, 9.985591536804074)

### 补充内容

In [18]:
np.ptp(X)

19.0

In [19]:
q = np.linspace(0, 100, 5)

In [20]:
q, np.percentile(X, q)

(array([  0.,  25.,  50.,  75., 100.]),
 array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ]))

In [21]:
np.cumsum(X, axis = 1)

array([[ 1.,  3.,  6., 10., 15.],
       [ 6., 13., 21., 30., 40.],
       [11., 23., 36., 50., 65.],
       [16., 33., 51., 70., 90.]])

In [22]:
np.diff(X, axis = 1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.prod(X, axis = 1)

array([1.20000e+02, 3.02400e+04, 3.60360e+05, 1.86048e+06])