## 最大值 最小值

In [1]:
import numpy as np 
x = np.random.normal(0,1,size=1000000)
x

array([ 0.62116468,  0.06087828, -0.79739964, ..., -0.39959928,
        0.03159948,  0.69490576])

In [2]:
np.min(x)

-5.681742531101642

In [3]:
np.argmin(x)

201552

In [4]:
x[286411]

-0.6958937983899646

In [5]:
np.max(x)

5.030748596384708

In [6]:
x[np.argmax(x)]

5.030748596384708

## 排序

In [7]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.random.shuffle(x)
x

array([9, 8, 7, 5, 1, 4, 0, 6, 2, 3])

In [9]:
np.sort(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
x

array([9, 8, 7, 5, 1, 4, 0, 6, 2, 3])

In [11]:
x.sort()

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 使用索引

In [14]:
np.random.shuffle(x)
x

array([6, 7, 9, 5, 2, 1, 8, 0, 3, 4])

In [15]:
np.argsort(x)

array([7, 5, 4, 8, 9, 3, 0, 1, 6, 2])

## partition 分区

In [16]:
np.partition(x, 5)

array([1, 2, 3, 0, 4, 5, 6, 8, 9, 7])

In [17]:
np.argpartition(x, 5)

array([5, 4, 8, 7, 9, 3, 0, 6, 2, 1])

## 高维情况

In [18]:
X = np.random.randint(10, size=(5,5))
X

array([[8, 0, 8, 9, 6],
       [2, 8, 4, 1, 1],
       [1, 9, 2, 3, 9],
       [2, 3, 4, 1, 4],
       [8, 1, 3, 4, 5]])

In [19]:
np.sort(X)

array([[0, 6, 8, 8, 9],
       [1, 1, 2, 4, 8],
       [1, 2, 3, 9, 9],
       [1, 2, 3, 4, 4],
       [1, 3, 4, 5, 8]])

In [20]:
np.argsort(X, axis=1)

array([[1, 4, 0, 2, 3],
       [3, 4, 0, 2, 1],
       [0, 2, 3, 1, 4],
       [3, 0, 1, 2, 4],
       [1, 2, 3, 4, 0]])

In [21]:
np.partition(X,2, axis=1)

array([[0, 6, 8, 9, 8],
       [1, 1, 2, 4, 8],
       [1, 2, 3, 9, 9],
       [1, 2, 3, 4, 4],
       [1, 3, 4, 8, 5]])

In [22]:
np.argpartition(X,2,axis=1)

array([[1, 4, 2, 3, 0],
       [3, 4, 0, 2, 1],
       [0, 2, 3, 1, 4],
       [3, 0, 1, 2, 4],
       [1, 2, 3, 0, 4]])