## 神奇索引

In [1]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
x[2:8]

array([2, 3, 4, 5, 6, 7])

In [3]:
x[2:8:2]

array([2, 4, 6])

In [4]:
[x[2],x[5],x[8]]

[2, 5, 8]

In [5]:
index = [2,5,8]
x[index]

array([2, 5, 8])

In [6]:
index = np.array([[1,3,5],[2,4,6]])
x[index]

array([[1, 3, 5],
       [2, 4, 6]])

## 神奇索引用于二维数组

In [7]:
X = x.reshape(2,-1)
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
row = np.array([0,1,0])
col = np.array([0,2,4])
X[row,col]

array([0, 7, 4])

In [9]:
X[0,col]

array([0, 2, 4])

In [10]:
X[row,:2]

array([[0, 1],
       [5, 6],
       [0, 1]])

In [11]:
col = [True, False, True, False, True]
X[0,col]

array([0, 2, 4])

## 比较

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [14]:
x >=2 

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [15]:
x==3

array([False, False, False,  True, False, False, False, False, False,
       False])

In [16]:
x!=3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [17]:
x*x==9

array([False, False, False,  True, False, False, False, False, False,
       False])

In [18]:
X>1

array([[False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 比较结果和神奇索引的使用

In [19]:
x[x>3]

array([4, 5, 6, 7, 8, 9])

In [20]:
x[x%2==0]

array([0, 2, 4, 6, 8])

## 比较的更多应用

In [21]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.count_nonzero(x<5)

5

In [23]:
x<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [24]:
np.sum(x<5)

5

In [25]:
np.any(x<0)

False

In [26]:
np.any(x>5)

True

In [27]:
np.all(x>0)

False

In [28]:
np.all(x<10)

True

In [29]:
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
np.sum(X%2==0)

5

In [31]:
np.sum(X%2==0, axis=1)

array([3, 2])

In [32]:
np.sum(X%2==0, axis=0)

array([1, 1, 1, 1, 1])

In [33]:
np.all(X>2, axis=0)

array([False, False, False,  True,  True])

## 与& 或| 非~

In [34]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.sum((x<5)&(x>1))

3

In [36]:
np.sum((x<1)|(x>6))

4

In [37]:
np.sum(~(x==0))

9