# 导入numpy

In [1]:
import numpy as np

# 创建Numpy数组

In [2]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
A = np.array(
    [
        [1,2,3],
        [5,6,7]
    ]
)
A

array([[1, 2, 3],
       [5, 6, 7]])

# Numpy数组的属性

In [4]:
a.ndim

1

In [5]:
A.ndim

2

In [6]:
a.shape

(6,)

In [7]:
A.shape

(2, 3)

In [8]:
a.size

6

In [9]:
A.size

6

In [10]:
a.dtype

dtype('int64')

In [11]:
A.dtype

dtype('int64')

# 创建数组的便捷函数

## ones

In [12]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones(8).dtype

dtype('float64')

In [14]:
np.ones(8,dtype='int64')

array([1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.ones_like(A)

array([[1, 1, 1],
       [1, 1, 1]])

## zeros

In [17]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0]])

## full

In [20]:
np.full(8,666)

array([666, 666, 666, 666, 666, 666, 666, 666])

In [21]:
np.full((2,4),666)

array([[666, 666, 666, 666],
       [666, 666, 666, 666]])

In [22]:
np.full_like(A, 666)

array([[666, 666, 666],
       [666, 666, 666]])

## empty

In [23]:
np.empty(8)

array([2.05186965e-316, 0.00000000e+000, 2.41907520e-312, 2.44029516e-312,
       2.29175545e-312, 2.27053550e-312, 8.48798317e-313, 8.70018275e-313])

In [24]:
np.empty((2,4))

array([[2.05186965e-316, 0.00000000e+000, 2.41907520e-312,
        2.44029516e-312],
       [2.29175545e-312, 2.27053550e-312, 8.48798317e-313,
        8.70018275e-313]])

In [25]:
np.empty_like(A)

array([[49785536,        0,        0],
       [       0,        0,        0]])

## arange

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [28]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## linspace

In [29]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# random模块

## random

In [30]:
np.random.random()

0.6160962522468241

In [31]:
np.random.random(5)

array([0.84127341, 0.48222372, 0.90828922, 0.36954664, 0.22532067])

In [32]:
np.random.random((2,4))

array([[0.27181514, 0.15703565, 0.31419621, 0.08382473],
       [0.54159785, 0.63871858, 0.66251797, 0.62471311]])

## rand

In [33]:
np.random.rand()

0.8774587965932436

In [34]:
np.random.rand(5)

array([0.13384554, 0.21306594, 0.30306473, 0.18566478, 0.69966918])

In [35]:
np.random.rand(2,4,3)

array([[[0.59717132, 0.00826123, 0.29273091],
        [0.37695511, 0.47300885, 0.4161377 ],
        [0.10521003, 0.45477703, 0.38927769],
        [0.96095509, 0.52454654, 0.55049337]],

       [[0.79916878, 0.03631291, 0.93487382],
        [0.251527  , 0.42738936, 0.8647998 ],
        [0.32140807, 0.06587076, 0.72579955],
        [0.1023671 , 0.05277878, 0.64963486]]])

## randint

In [36]:
np.random.randint(5)

1

In [37]:
np.random.randint(5,10)

9

In [38]:
np.random.randint(5,10,size=8)

array([6, 5, 5, 5, 6, 9, 6, 6])

In [39]:
np.random.randint(5,10,size=(2,4))

array([[8, 6, 5, 7],
       [9, 5, 9, 9]])

## seed

In [40]:
np.random.seed(666)
np.random.randint(5,10,size=(2,4))

array([[9, 7, 6, 9],
       [8, 8, 9, 9]])

# randn

In [41]:
np.random.randn(5)

array([ 0.01902826, -0.94376106,  0.64057315, -0.78644317,  0.60886999])

In [42]:
np.random.randn(2,4)

array([[-0.93101185,  0.97822225, -0.73691806, -0.29873262],
       [-0.46058737, -1.08879299, -0.57577075, -1.68290077]])

# normal

In [43]:
np.random.normal()

0.2291852477040214

In [44]:
np.random.normal(10,100,20)

array([-165.66252234,   94.46326187,   37.72198634,   95.2901533 ,
         29.4599603 ,  141.06377157,  164.38436001,  -42.90480243,
        -55.64722973,  -10.15057011,  -60.06158328,   78.71379544,
          7.39242436,  -72.97583197,   39.65537839,  -21.26795036,
        -51.13012744,  -72.17515048,   99.71227031,   23.60786118])

In [45]:
np.random.normal(10,100,size=(4,5))

array([[ -15.86548011,  121.07656409,   -8.84243873,    5.85107071,
         -88.47919123],
       [-125.22817585,   29.43238455,   36.72393512,  -32.64736981,
         154.77350574],
       [  -9.63061002,  161.814514  ,   17.72218828,    3.60086759,
         104.59234072],
       [ 130.40910055,  -35.12407353, -148.74465098, -176.88554809,
          20.03773732]])

## uniform

In [46]:
np.random.uniform()

0.5018935081312759

In [47]:
np.random.uniform(1,5)

2.993092519645257

In [48]:
np.random.uniform(1,5,(3,4))

array([[1.4150861 , 2.78577246, 4.87675667, 3.95388449],
       [3.87820243, 4.57217355, 4.85069873, 1.78820091],
       [3.85835986, 1.64769576, 4.46501909, 3.49528099]])

In [49]:
np.random.uniform?

In [50]:
help(np.random.uniform)

Help on built-in function uniform:

uniform(...) method of numpy.random.mtrand.RandomState instance
    uniform(low=0.0, high=1.0, size=None)
    
    Draw samples from a uniform distribution.
    
    Samples are uniformly distributed over the half-open interval
    ``[low, high)`` (includes low, but excludes high).  In other words,
    any value within the given interval is equally likely to be drawn
    by `uniform`.
    
    .. note::
        New code should use the ``uniform`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : float or array_like of floats, optional
        Lower boundary of the output interval.  All values generated will be
        greater than or equal to low.  The default value is 0.
    high : float or array_like of floats
        Upper boundary of the output interval.  All values generated will be
        less than or equal to high.  The high limit may be included in t