# 基础索引

In [1]:
import numpy as np

In [2]:
# 一维数组  也看作：向量
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 二维数组 看作是：矩阵
A = np.arange(20).reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 一维数组

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a[0]

0

In [6]:
a[4]

4

In [7]:
a[-1]

9

In [8]:
a[0:5]

array([0, 1, 2, 3, 4])

In [9]:
a[:5]

array([0, 1, 2, 3, 4])

In [10]:
a[4:]

array([4, 5, 6, 7, 8, 9])

In [11]:
a[-3:]

array([7, 8, 9])

In [12]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 二维数组

In [14]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
A[0,0]

0

In [16]:
A[0,:]

array([0, 1, 2, 3, 4])

In [17]:
A[0]

array([0, 1, 2, 3, 4])

In [18]:
A[-1]

array([15, 16, 17, 18, 19])

In [19]:
A[:,0]

array([ 0,  5, 10, 15])

In [20]:
A[:,-1]

array([ 4,  9, 14, 19])

In [21]:
A[:2,:4]

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [22]:
A[::-1,::-1]

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [23]:
X = A[:2,:3]
X

array([[0, 1, 2],
       [5, 6, 7]])

In [24]:
X[0,0] = 666
X

array([[666,   1,   2],
       [  5,   6,   7]])

In [25]:
A

array([[666,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [26]:
A[0,0] = 0
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
X

array([[0, 1, 2],
       [5, 6, 7]])

In [28]:
X = A[:2,:3].copy()
X

array([[0, 1, 2],
       [5, 6, 7]])

In [29]:
X[0,0] = 666
X

array([[666,   1,   2],
       [  5,   6,   7]])

In [30]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])