# 数组的合并

In [1]:
import numpy as np

In [2]:
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
a = np.array([6,6,6,6])
a

array([6, 6, 6, 6])

In [4]:
np.concatenate((X,a))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [5]:
np.concatenate((X,a.reshape(1,4)))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 6,  6,  6,  6]])

In [6]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a

array([6, 6, 6, 6])

In [8]:
A = np.concatenate((X,a.reshape(1,4)))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 6,  6,  6,  6]])

In [9]:
np.vstack((X,a))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 6,  6,  6,  6]])

In [10]:
B = np.full((3,2),666)
B

array([[666, 666],
       [666, 666],
       [666, 666]])

In [11]:
np.hstack((X,B))

array([[  0,   1,   2,   3, 666, 666],
       [  4,   5,   6,   7, 666, 666],
       [  8,   9,  10,  11, 666, 666]])

In [12]:
np.concatenate((X,B),axis=1)

array([[  0,   1,   2,   3, 666, 666],
       [  4,   5,   6,   7, 666, 666],
       [  8,   9,  10,  11, 666, 666]])

# 数组的拆分

In [13]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
np.split(X,[-1], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

In [15]:
X1,X2 = np.split(X,[-1], axis=1)

In [16]:
X1

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [17]:
X2

array([[ 3],
       [ 7],
       [11]])

In [18]:
np.vsplit(X,[2])   

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

In [19]:
X1, X2, X3 = np.hsplit(X,[1,3])  

In [20]:
X1

array([[0],
       [4],
       [8]])

In [21]:
X2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [22]:
X3

array([[ 3],
       [ 7],
       [11]])