## 数据准备

In [1]:
import numpy as np
state = np.array(['认真复习', '简单复习', '没有复习'])
grade = np.array(['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-'])
n_state = len(state)
m_grade = len(grade)
pi = np.ones(n_state)/n_state
t = np.array([
    [0.4, 0.3, 0.3],
    [0.3, 0.4, 0.3],
    [0.3, 0.3, 0.4]
])
e = np.zeros([3,9])
e[0, :9]=1/9
e[1, 3:9]=1/6
e[2, 5:9]=1/4

In [2]:
print("初始概率矩阵：\n",pi)
print("转移矩阵：\n",t)
print("发射矩阵：\n",e)

初始概率矩阵：
 [0.33333333 0.33333333 0.33333333]
转移矩阵：
 [[0.4 0.3 0.3]
 [0.3 0.4 0.3]
 [0.3 0.3 0.4]]
发射矩阵：
 [[0.11111111 0.11111111 0.11111111 0.11111111 0.11111111 0.11111111
  0.11111111 0.11111111 0.11111111]
 [0.         0.         0.         0.16666667 0.16666667 0.16666667
  0.16666667 0.16666667 0.16666667]
 [0.         0.         0.         0.         0.         0.25
  0.25       0.25       0.25      ]]


## hmmlearn

In [3]:
pip install hmmlearn

Looking in indexes: http://mirrors.tencentyun.com/pypi/simple
Note: you may need to restart the kernel to use updated packages.


In [4]:
from hmmlearn.hmm import CategoricalHMM
hmm = CategoricalHMM(n_state)

In [5]:
hmm.startprob_ = pi
hmm.transmat_ = t
hmm.emissionprob_ = e
hmm.n_feature = 9

In [6]:
datas = np.array([0, 4, 2, 6, 1])
datas = np.expand_dims(datas, axis=1)
states = hmm.predict(datas)

In [7]:
states

array([0, 0, 0, 2, 0])

In [8]:
prob = hmm.score(datas)
prob

-14.003674820375014

In [9]:
print(np.exp(prob))

8.284786081615825e-07


In [10]:
datas , states = hmm.sample(10000)

In [11]:
t_2 = np.zeros([3,3])
for i in range(3):
    current = np.where(states == i)[0]
    next_index = current+1
    next_index = next_index[:-1]

    tmp = states[next_index]
    for j in range(3):
        t_2[i][j] = np.where(tmp==j)[0].shape[0]/np.shape(tmp)[0]
print(t_2)

[[0.41121495 0.29333735 0.29544769]
 [0.28884285 0.40988458 0.30127257]
 [0.29627386 0.30930021 0.39442593]]


In [12]:
e_2 = np.zeros([3,9])
for i in range(3):
    current = np.where(states == i)[0]
    next_index = current+1
    next_index = next_index[:-1]
    tmp = datas[current]
    for j in range(9):
        e_2[i][j] = np.where(tmp==j)[0].shape[0]/np.shape(tmp)[0]
print(e_2)

[[0.10518385 0.10066305 0.11030741 0.11603376 0.11000603 0.1106088
  0.12115732 0.12085594 0.10518385]
 [0.         0.         0.         0.1760355  0.15591716 0.16242604
  0.17071006 0.16952663 0.16538462]
 [0.         0.         0.         0.         0.         0.24863719
  0.25741975 0.24500303 0.24894004]]
